name: Lint
on: [push]
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Set up Poetry cache for Python dependencies
      uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry-
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dev deps
      run: |
        poetry config settings.virtualenvs.in-project true
        poetry install --only dev
    - name: Check lint
      run: make lint