name: Lint
on: [push]
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Set up Poetry cache for Python dependencies
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.venv
        key: dependencies-${{ hashFiles('**/poetry.lock') }}
        restore-keys: dependencies-
    - name: Install deps poetry
      if: steps.cache-dependencies.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install --with dev --no-interaction --no-ansi
    - name: Check lint
      run: poetry run make lint