name: lint
on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-actions
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
          env-groups: "lint"

      - name: Check lint
        run: poetry run make lint
